# Generated by Django 3.0.4 on 2020-05-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_counter',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
